/**
 * Deploy AiPet to the hosted GenLayer Studio sandbox and drive it live.
 *
 *   npm install
 *   npm run deploy:studio:live
 *
 * No Docker and no `genlayer` CLI needed: Studio exposes a public RPC
 * (https://studio.genlayer.com/api) and genlayer-js talks to it directly.
 * A throwaway account is generated on each run — Studio does not charge gas.
 *
 * What this proves: the contract deploys on a real network, and check() makes a
 * REAL open-meteo request and a REAL LLM call, both settled through consensus.
 *
 * What it CANNOT prove: anything involving value — feed() with GEN, revive(),
 * withdraw(), the feeder leaderboard. Studio does not support token transfers.
 * Use localnet (`genlayer up`) or Testnet Bradbury for those.
 */
import { readFileSync, writeFileSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { buildContract } from "../lib/buildContract.mjs";
import { createClient, createAccount, generatePrivateKey } from "genlayer-js";
import { studionet } from "genlayer-js/chains";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const CONTRACT = path.resolve(HERE, "../contracts/ai_pet.py");
const SESSION = path.resolve(HERE, "../.studio-session.json");

// The DEPLOY ARTIFACT, not the source: Bradbury refuses a deploy over ~52 KB and
// contracts/ai_pet.py is past that with its comments. See lib/buildContract.mjs.
const built = buildContract(CONTRACT);
const contractCode = built.code;

const CTOR = ["Pixel", "a sleepy philosopher cat who speaks in riddles", "Lisbon"];
const ACTIONS = ["check", "play", "pet"];

const pk = generatePrivateKey();
const account = createAccount(pk);
const client = createClient({ chain: studionet, account });
console.log("account:", account.address);

const settle = (hash) =>
  client.waitForTransactionReceipt({
    hash,
    status: "FINALIZED",
    retries: 400,
    interval: 3000,
  });

console.log("deploying…");
const receipt = await settle(
  await client.deployContract({
    code: contractCode,
    args: CTOR,
  }),
);
const address =
  receipt?.data?.contract_address ?? receipt?.txDataDecoded?.contractAddress;
if (!address) {
  console.error("no contract address in receipt:", JSON.stringify(receipt).slice(0, 1000));
  process.exit(1);
}
console.log("deployed:", address);
writeFileSync(SESSION, JSON.stringify({ address, account: account.address, pk }, null, 1));

const read = (fn, args = []) => client.readContract({ address, functionName: fn, args });

async function show(label) {
  const s = await read("get_state");
  console.log(`\n=== ${label} ===`);
  console.log(`  🐾 "${s.last_quote}"`);
  console.log(
    `  satiety ${s.satiety} | mood ${s.mood} | health ${s.health} | ${s.stage} ${s.age_days}d | alive ${s.alive}`,
  );
}

await show("after deploy");

for (const fn of ACTIONS) {
  const t0 = Date.now();
  console.log(`\n>>> ${fn}() … (real web/LLM — expect ~40-60 s)`);
  const r = await settle(
    await client.writeContract({ address, functionName: fn, args: [], value: 0n }),
  );
  console.log(`    ${r.statusName ?? r.status} in ${((Date.now() - t0) / 1000).toFixed(1)}s`);
  await show(`after ${fn}()`);
}

console.log("\n--- lines feed (generated by a real LLM, on-chain) ---");
for (const [i, q] of (await read("get_history")).entries()) console.log(`  ${i + 1}. ${q}`);
console.log(`\nSession written to ${SESSION} — paste the address into the frontend to keep playing.`);
